name: Build App Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Basic test
        run: echo "app-deploy works"

      - uses: actions/checkout@v4

      - name: Docker test
        run: docker --version
