name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login and build
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login git.unveiledsoftwaresolutions.com -u ${{ github.actor }} --password-stdin
          docker build -t git.unveiledsoftwaresolutions.com/jariah/ateliercode-app:test .
          echo "Build complete"
